#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

// fcgi doesn't have STDIN and STDOUT defined by default
defined('STDIN') or define('STDIN', fopen('php://stdin', 'r'));
defined('STDOUT') or define('STDOUT', fopen('php://stdout', 'w'));

if (!file_exists(__DIR__ . '/config/local.php')) {
    fwrite(STDOUT, \yii\helpers\Console::ansiFormat('ERROR: Local config file not found!', [\yii\helpers\Console::BG_RED]) . PHP_EOL);
    exit(1);
}
$local = require(__DIR__ . '/config/local.php');
if (isset($local['params']) && isset($local['params']['debug']) && $local['params']['debug'] === true) {
    defined('YII_DEBUG') or define('YII_DEBUG', true);
} else {
    defined('YII_DEBUG') or define('YII_DEBUG', false);
}

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');


$config = require(__DIR__ . '/config/console.php');
$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
